server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    max-connections: 10000
    threads:
      max: 2500
      min-spare: 100

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 3000
        max-idle: 100
        max-wait: 2500
        min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/filedb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

file:
  storage:
    #存储类型
    type: fastdfs
  #fastdfs 配置
  fastdfs:
    tracker-servers: 192.168.248.101:22122
  #文件上传配置
  upload:
    #普通上传文件最大值
    max-upload-size: 10MB
    #分上传文件最小值 小于5M minio会上传错误
    multipart-min-size: 5MB
    #分上传文件最大值
    multipart-max-size: 100MB
  ali:
    endpoint:
    access-key:
    secret-key:
    bucket-name:

#swagger配置
knife4j:
  #开启增强
  enable: true
